# Generated by Django 6.0.3 on 2026-03-15 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_cloudinaryimage_cloudinaryrendition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.cloudinaryimage'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Homepage image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.cloudinaryimage'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.cloudinaryimage'),
        ),
    ]
